# Generated by Django 3.1.3 on 2020-12-30 20:03

from django.db import migrations, models
import movieapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clips',
            options={'verbose_name': 'Clip', 'verbose_name_plural': 'Clips'},
        ),
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name': 'Movie', 'verbose_name_plural': 'Movies'},
        ),
        migrations.AlterModelOptions(
            name='series',
            options={'verbose_name': 'Series', 'verbose_name_plural': 'Series'},
        ),
        migrations.AddField(
            model_name='clips',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='movies',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AddField(
            model_name='series',
            name='slug',
            field=models.SlugField(default=None),
        ),
        migrations.AlterField(
            model_name='clips',
            name='clip_file',
            field=models.FileField(max_length=1000, upload_to=movieapp.models.update_clip_name),
        ),
        migrations.AlterField(
            model_name='movies',
            name='movie_file',
            field=models.FileField(max_length=1000, upload_to=movieapp.models.update_movie_name),
        ),
        migrations.AlterField(
            model_name='movies',
            name='poster_img',
            field=models.ImageField(max_length=1000, upload_to=movieapp.models.update_movie_poster_name),
        ),
        migrations.AlterField(
            model_name='series',
            name='poster_img',
            field=models.ImageField(max_length=1000, upload_to=movieapp.models.update_series_poster_name),
        ),
        migrations.AlterField(
            model_name='series',
            name='series_file',
            field=models.FileField(max_length=1000, upload_to=movieapp.models.update_series_name),
        ),
    ]
